all: myPS myPS_v0 myPS2 myPS3 parsexec

myPS: myPS.c
	gcc -o myPS myPS.c

myPS_v0: myPS_v0.c
	gcc -o myPS_v0 myPS_v0.c

myPS2: myPS2.c
	gcc -o myPS2 myPS2.c

myPS3: myPS3.c
	gcc -o myPS3 myPS3.c

parsexec: parsexec.c
	gcc -o parsexec parsexec.c
clean:
	rm myPS
	rm myPS_v0
	rm myPS2
	rm myPS3
	rm parsexec
